### ISSUE TITLE
Debug logging

### ISSUE THREAD

**Issue by dragoangel** [prometheus/cloudwatch_exporter#358] opened 2021-09-07 11:43 UTC
If I want to run cloudwatch_exporter in debug mode deployed in docker image I can't pass -d or --debug key to the command as it will treated as part of config name. No matter where I will put this key, before or after config, no matter how I will add "" to escape config path, it will throw:
```
Exception in thread "main" java.io.FileNotFoundException: -d "/config/cloudwatch-ap-northeast-1.yml" (No such file or directory)
```

**Comment by dragoangel** [comment] 2021-09-07 11:47
Maybe environment variable can be used to enable debug logging or fix to argument parser can be applied.

**Comment by stuart-c** [comment] 2021-09-07 11:51
It looks like you want to be overriding the entrypoint rather than the command

**Comment by dragoangel** [comment] 2021-09-07 11:58
Oh, looks like debug logging isn't merged, it closed without implementing, or I missed something? https://github.com/prometheus/cloudwatch_exporter/pull/225
I run now not dockerized version and can't get it works also

**Comment by dragoangel** [comment] 2021-09-07 12:12
Just to note why I need debug logging: https://groups.google.com/g/prometheus-users/c/g7cRV15f7iE

**Comment by matthiasr** [comment] 2021-11-26 15:39
Thank you, I agree that we should do better on debug logging. I will reconsider the existing approaches, and see what I want to do. In the meantime, I'm going to close this issue as it is a duplicate of #181.

**Closed by matthiasr** 2021-11-26 15:39 UTC
Labels: duplicate, enhancement
