### ISSUE TITLE
Select multiple dimension

### ISSUE THREAD

**Issue by sujithpaily** [prometheus/cloudwatch_exporter#147] opened 2018-10-22 08:53 UTC
Does  aws_dimension_select support multiple dimensions?

I need to pass following request via exporter config

aws cloudwatch get-metric-statistics --namespace "CWAgent" --metric-name "mem_used_percent" --dimensions Name=InstanceId,Value=i-03a1b963cd00a5cff Name=ImageId,Value=ami-0ac019f4fcb7cb7e6 Name=InstanceType,Value=t2.small --start-time 2018-10-20T08:40:00Z --end-time 2018-10-20T08:45:00Z --period 60 --statistics Average

**Comment by brian-brazil** [comment] 2018-10-22 12:29
Dupe of #148

**Closed by brian-brazil** 2018-10-22 12:29 UTC
