### ISSUE TITLE
[request]: Improve logging

### ISSUE THREAD

**Issue by gnadaban** [prometheus/cloudwatch_exporter#462] opened 2022-10-20 19:09 UTC
# Proposal

As an operator deploying and maintaining `cloudwatch-exporter` I want to be able to diagnose eg. why it is crashlooping. For this, I need to be able to configure various log levels and expect to see detailed logs about what the application is attempting to do and why it is failing.

###  Use case. Why is this important?

Deploying the `0.15.0` version in Kubernetes with the latest [0.22.0 Helm chart](https://github.com/prometheus-community/helm-charts/tree/prometheus-cloudwatch-exporter-0.22.0/charts/prometheus-cloudwatch-exporter) results in a crashloop.

Without logs it is impossible to understand why the health and readyiness checks are failing.

Example log of a crashlooping pod:

> Oct 20, 2022 7:01:56 PM org.eclipse.jetty.server.Server doStart
INFO: jetty-11.0.9; built: 2022-03-30T17:44:47.085Z; git: 243a48a658a183130a8c8de353178d154ca04f04; jvm 17.0.4.1+1
Oct 20, 2022 7:01:56 PM org.eclipse.jetty.server.handler.ContextHandler doStart
INFO: Started o.e.j.s.ServletContextHandler@1de5f0ef{/,null,AVAILABLE}
Oct 20, 2022 7:01:56 PM org.eclipse.jetty.server.AbstractConnector doStart
INFO: Started ServerConnector@710b18a6{HTTP/1.1, (http/1.1)}{0.0.0.0:9106}
Oct 20, 2022 7:01:56 PM org.eclipse.jetty.server.Server doStart
INFO: Started Server@57fd91c9{STARTING}[11.0.9,sto=0] @2082ms

Describing the crashlooping pod shows events about readiness check failing:

```
  Normal   Started    40s (x2 over 92s)  kubelet            Started container prometheus-cloudwatch-exporter
  Warning  Unhealthy  40s                kubelet            Readiness probe failed: Get "http://10.0.9.39:9106/-/ready": read tcp 10.0.9.76:42842->10.0.9.39:9106: read: connection reset by peer
  Warning  Unhealthy  40s                kubelet            Readiness probe failed: Get "http://10.0.9.39:9106/-/ready": dial tcp 10.0.9.39:9106: connect: connection refused
  Warning  Unhealthy  2s (x5 over 57s)   kubelet            Readiness probe failed: Get "http://10.0.9.39:9106/-/ready": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy  2s (x4 over 57s)   kubelet            Liveness probe failed: Get "http://10.0.9.39:9106/-/healthy": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

Interestingly, configuring the below env var seems to resolve something such that the app now responds to readiness checks:
```yaml
            - name: JAVA_OPTIONS
              value: '-Dorg.eclipse.jetty.http.LEVEL=DEBUG'
```

Logs don't show any information whatsoever between starting the pod and becoming ready:
```
Oct 20, 2022 7:06:57 PM org.eclipse.jetty.server.Server doStart
INFO: jetty-11.0.9; built: 2022-03-30T17:44:47.085Z; git: 243a48a658a183130a8c8de353178d154ca04f04; jvm 17.0.4.1+1
Oct 20, 2022 7:06:57 PM org.eclipse.jetty.server.handler.ContextHandler doStart
INFO: Started o.e.j.s.ServletContextHandler@5ef0d29e{/,null,AVAILABLE}
Oct 20, 2022 7:06:57 PM org.eclipse.jetty.server.AbstractConnector doStart
INFO: Started ServerConnector@25e2ab5a{HTTP/1.1, (http/1.1)}{0.0.0.0:9106}
Oct 20, 2022 7:06:57 PM org.eclipse.jetty.server.Server doStart
INFO: Started Server@5c8eee0f{STARTING}[11.0.9,sto=0] @1992ms
```

Any improvement in logging would be super useful for operators. 🙏🏼

**Comment by gnadaban** [comment] 2022-10-20 19:29
On further investigation, the log level setting did not seem to have any effect. It would seem that the app often takes a lot longer to start up and respond to health and readiness checks than what's configured in the Helm chart.

**Comment by matthiasr** [comment] 2022-10-25 08:13
Hmm, that seems odd – are you [using CPU limits](https://home.robusta.dev/blog/stop-using-cpu-limits/)?

Since this is caused by the liveness probe killing the container, there's nothing logging can do to help. I'll close this issue to avoid conflating things. However, for the record, I am very open to improving logging where it is incomplete or confusing!

**Closed by matthiasr** 2022-10-25 08:13 UTC
Labels: enhancement
