### ISSUE TITLE
Feature: Default value if metric not found

### ISSUE THREAD

**Issue by 3h4x** [prometheus/cloudwatch_exporter#92] opened 2018-03-05 15:47 UTC
Hey,

Problem: we don't have reliable way to create meaningful alerts because unavailability of metric can cause that it won't fire when it should.

Example:
We are  scraping metrics from ELB httpcode: 2xx, 3xx, 4xx and 5xx.
To get an idea of the traffic coming through we would like to do (pseudo query) `2xx + 3xx + 4xx + 5xx`. This will fail if any of the metric don't have data returning "no data".

Either the exporter should provide me a way to set default value or prometheus.

Is there a way around it?

**Comment by brian-brazil** [comment] 2018-03-05 15:58
Dupe of #87

**Closed by brian-brazil** 2018-03-05 15:58 UTC

**Comment by 3h4x** [comment] 2018-03-05 16:15
I think you have closed it prematurely without explaining what are the best practices in that case.

I can't use `clamp_min`, exporter is returning chopped data, I would like my metrics to be reliable and I cannot rely on it at this stage. What are you proposing other than closing this issue?

**Comment by brian-brazil** [comment] 2018-03-05 16:18
This is fundamentally an issue with Cloudwatch.

https://www.robustperception.io/existential-issues-with-metrics/

**Comment by kminehart** [comment] 2018-11-05 22:06
The documentation you linked to in your blog post clearly says,

> Time series that are not present until something happens are difficult to deal with, as the usual simple operations are no longer sufficient to correctly handle them. *To avoid this, export 0 (or NaN, if 0 would be misleading) for any time series you know may exist in advance.*

This should be re-opened, imo. Unfortunately we can't expect Amazon to fix CloudWatch.
